version: "3.8"
services:
  binance-postgres:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "binance"
      POSTGRES_USER: "binance"
      POSTGRES_PASSWORD: "binance"
    volumes:
      - /root/db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "5432:5432"
  binance:
    image: binance/binance:0.0.2
    depends_on:
      - binance-postgres
