version: "3.9"

networks:
  grafana_loki:

services:

  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - 3000:3000
    networks:
      - grafana_loki

  loki:
    image: grafana/loki:2.5.0
    ports:
      - "3100:3100"
    volumes:
      - ${BINANCE_LOKI}:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - grafana_loki

  binance-postgres:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "binance"
      POSTGRES_USER: "binance"
      POSTGRES_PASSWORD: "binance"
    volumes:
      - ${BINANCE_PG_INIT_DB}:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "5432:5432"
    networks:
      - grafana_loki

  binance-mongodb:
    image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: "binance"
      MONGO_INITDB_ROOT_PASSWORD: "binance"
    ports:
      - "27017:27017"
    networks:
      - grafana_loki

  binance:
    image: binance/binance:${BINANCE_VERSION}
    environment:
      APP_NAME: ${BINANCE_APP_NAME}
      LOG_LEVEL: ${BINANCE_LOG_LEVEL}
    depends_on:
      - binance-postgres
      - binance-mongodb
    restart: always
    ports:
      - ${BINANCE_APP_PORT}:8080
    networks:
      - grafana_loki