version: "3.8"
services:
  binance-postgres:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "binance"
      POSTGRES_USER: "binance"
      POSTGRES_PASSWORD: "binance"
    volumes:
      - ${BINANCE_PG_INIT_DB}:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "5432:5432"

  binance:
    image: binance/binance:${BINANCE_VERSION}
    depends_on:
      - binance-postgres
    ports:
      - ${BINANCE_APP_PORT}:8080