version: "3.9"

networks:
  binance_network:

services:
#  prometheus:
#    image: prom/prometheus:v2.38.0
#    volumes:
#      - ${BINANCE_PROMETHEUS}:/etc/prometheus/prometheus-config.yaml
#    container_name: prometheus
#    hostname: prometheus
#    command:
#      - --config.file=/etc/prometheus/prometheus-config.yaml
#    ports:
#      - "9090:9090"
#    restart: unless-stopped
#    environment:
#      TZ: "Europe/Moscow"
#    networks:
#      - binance_network

#  loki:
#    image: grafana/loki:2.5.0
#    container_name: loki
#    hostname: loki
#    ports:
#      - "3100:3100"
#    restart: unless-stopped
#    volumes:
#      - ${BINANCE_LOKI}:/etc/loki/local-config.yaml
#    command: -config.file=/etc/loki/local-config.yaml
#    networks:
#      - binance_network

#  grafana:
#    image: grafana/grafana-oss:9.1.2
#    container_name: grafana
#    hostname: grafana
#    ports:
#      - "3000:3000"
#    restart: unless-stopped
#    networks:
#      - binance_network
#    depends_on:
#      - prometheus
#      - loki

  postgres:
    image: postgres:14.5
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_DB: "binance"
      POSTGRES_USER: "binance"
      POSTGRES_PASSWORD: "binance"
    volumes:
      - ${BINANCE_PG_INIT_DB}:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - binance_network

  mongodb:
    image: mongo:4.2
    container_name: mongodb
    hostname: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: "binance"
      MONGO_INITDB_ROOT_PASSWORD: "binance"
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks:
      - binance_network

  binance:
    image: binance/binance:${BINANCE_VERSION}
    container_name: binance
    hostname: binance
    environment:
      APP_NAME: ${BINANCE_APP_NAME}
      LOG_LEVEL: ${BINANCE_LOG_LEVEL}
    depends_on:
      - postgres
      - mongodb
    restart: unless-stopped
    ports:
      - ${BINANCE_APP_PORT}:8080
    networks:
      - binance_network