version: "3.8"
services:
  binance-postgres:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "binance"
      POSTGRES_USER: "binance"
      POSTGRES_PASSWORD: "binance"
    volumes:
      - ${BINANCE_PG_INIT_DB}:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "5432:5432"

  binance-mongodb:
    image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: "binance"
      MONGO_INITDB_ROOT_PASSWORD: "binance"
    ports:
      - "27017:27017"

  binance:
    image: binance/binance:${BINANCE_VERSION}
    environment:
      LOG_LEVEL: ${BINANCE_LOG_LEVEL}
    depends_on:
      - binance-postgres
      - binance-mongodb
#    restart: always
    ports:
      - ${BINANCE_APP_PORT}:8080