{
 "title": "Orders stat",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "rate_interval", "query": "1d" }
  ]
 },
 "panels": [
  {
   "title": "COMPLETE Orders",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "order_complete{}", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Filled Orders",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "order_stop_loss_limit_filled{}", "legendFormat": "{{__name__}}" },
    { "expr": "order_limit_maker_filled{}", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Orders Stat",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "order_limit_maker_filled{}", "legendFormat": "{{__name__}}" },
    { "expr": "order_stop_loss_limit_filled{}", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "New Price Plan",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "order_oso_new_price_plan{}", "legendFormat": "{{__name__}}" },
    { "expr": "order_limit_new_price_plan{}", "legendFormat": "{{__name__}}" }
   ]
  }
 ]
}