// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CryptoCtrl is an autogenerated mock type for the CryptoCtrl type
type CryptoCtrl struct {
	mock.Mock
}

// GetSignature provides a mock function with given fields: query
func (_m *CryptoCtrl) GetSignature(query string) string {
	ret := _m.Called(query)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(query)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewCryptoCtrl interface {
	mock.TestingT
	Cleanup(func())
}

// NewCryptoCtrl creates a new instance of CryptoCtrl. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCryptoCtrl(t mockConstructorTestingTNewCryptoCtrl) *CryptoCtrl {
	mock := &CryptoCtrl{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
